import { assert } from "chai";
import * as fs from "fs";
import path from "path";

import { ERRORS } from "../../../src/internal/core/errors-list";
import {
  loadQrlJsRuntime,
  loadQrlJsTxRuntime,
  readBundledRuntimeManifest,
} from "../../../src/internal/qrl/runtime";
import { expectHardhatError } from "../../helpers/errors";
import { useTmpDir } from "../../helpers/fs";

// The compiled bundle location used by src/internal/qrl/runtime.ts. Tests
// touching the bundled path are conditional on a bundle being present
// (generated by scripts/bundle-qrljs-runtime.js / npm pack).
const BUNDLE_PATH = path.join(
  __dirname,
  "..",
  "..",
  "..",
  "qrljs-runtime",
  "runtime.cjs"
);

describe("qrljs runtime resolver", function () {
  useTmpDir("qrljs-runtime-resolver");

  const envVar = "QRLJS_MONOREPO_PATH";
  let savedEnv: string | undefined;

  beforeEach(function () {
    savedEnv = process.env[envVar];
  });

  afterEach(function () {
    if (savedEnv === undefined) {
      delete process.env[envVar];
    } else {
      process.env[envVar] = savedEnv;
    }
  });

  it("a set override is authoritative: broken paths error instead of falling back", function () {
    // Even with a bundle available, an explicit override must never be
    // silently masked — a developer pointing at a stale/unbuilt checkout
    // has to see the real problem.
    const brokenPath = path.join(this.tmpDir, "not-a-checkout");

    expectHardhatError(
      () => loadQrlJsRuntime("qrlLocal", brokenPath),
      ERRORS.NETWORK.QRLJS_MONOREPO_UNAVAILABLE
    );

    process.env[envVar] = brokenPath;
    expectHardhatError(
      () => loadQrlJsRuntime("qrlLocal"),
      ERRORS.NETWORK.QRLJS_MONOREPO_UNAVAILABLE
    );
  });

  it("resolves a valid override checkout with source kind override", function () {
    if (process.env[envVar] === undefined) {
      this.skip();
    }

    const runtime = loadQrlJsRuntime("qrlLocal");
    assert.equal(runtime.source.kind, "override");
    assert.isDefined(runtime.vmQrl.QRLLocalProvider);
    assert.isDefined(runtime.utilQrl.QRLAddress);
  });

  it("falls back to the bundled runtime when no override is set", function () {
    if (!fs.existsSync(BUNDLE_PATH)) {
      this.skip();
    }

    delete process.env[envVar];
    const runtime = loadQrlJsRuntime("qrlLocal");
    assert.equal(runtime.source.kind, "bundled");
    assert.isDefined(runtime.vmQrl.QRLLocalProvider);
    assert.isDefined(runtime.utilQrl.QRLAddress);

    const txQrl = loadQrlJsTxRuntime();
    assert.isDefined(txQrl.QRLDynamicFeeTransaction);

    const manifest = readBundledRuntimeManifest();
    assert.isDefined(manifest);
    assert.isString(manifest.qrlJsCommit);
    assert.property(manifest.packageVersions, "@theqrl/vm");
  });

  it("errors actionably when neither override nor bundle is available", function () {
    if (fs.existsSync(BUNDLE_PATH)) {
      this.skip();
    }

    delete process.env[envVar];
    expectHardhatError(
      () => loadQrlJsRuntime("qrlLocal"),
      ERRORS.NETWORK.QRLJS_MONOREPO_UNAVAILABLE
    );
  });
});
